### ISSUE TITLE
Add support for javascript on Anki iOS

### ISSUE THREAD

**Issue by AnKingMed** [AnKing-Memberships/AnKing-Note-Types#110]
See this thread here: https://forums.ankiweb.net/t/can-we-update-anki-ios-to-focus-in-reviewer/23080/13

**Comment by AnKingMed** [comment]
@BlueGreenMagick would you have time to look into this?

**Comment by AnKingMed** [comment]
@abdnh I think @BlueGreenMagick may be busy so if you want to look into making this change, this might be a good way for you to familiarize yourself with the Anking note types and the [associated addon](https://github.com/AnKing-Memberships/anking_notes_addon)

**Comment by abdnh** [comment]
The goal here is to provide a GUI to map AnkiMobile's user actions to shortcuts like "Reveal cloze", right?

**Comment by AnKingMed** [comment]
Yeah so someone can use a keyboard on iPad.  Probably just need something like this: https://forums.ankiweb.net/t/can-we-update-anki-ios-to-focus-in-reviewer/23080/16?u=ankingmed

**Comment by abdnh** [comment]
Here is a UI mockup of how I imagine it should look like:
![image](https://user-images.githubusercontent.com/41397710/219771763-e5ac5961-d084-40b9-8420-be051a91f612.png)

**Comment by AnKingMed** [comment]
That looks pretty reasonable!
