### ISSUE TITLE
Error appears when creating normal cloze deletion

### ISSUE THREAD

**Issue by justarmadillo** [AnKing-Memberships/AnKing-Note-Types#111]
#### Problem description

After I have installed Closet addon to use it for IO one by one and when doing cloze card type (default anki cloze card type) and press **CTRL+SHIFT+C** to make cloze deletion the error message appears.
After the error appears, after that when I try to make IO one by one and after adding occlusions and selecting accept occlusions, the addon won't add the occlusions properties to IO field untill I restart anki and I make sure that I haven't created cloze by clicking on CTRL SHIFT C (trying to avoid error, after the error appears the occlusion feature stops working).
Please help me fix this problem
**NB:** when I create normal cloze with the button in the top bar in the editor the error doesn't appear, it only appears when I click on the shortcut CTRL SHIFT C

#### Checklist

 - [x] I've restarted Anki to see if it helps
 - [x] I've verified that I use the latest version of the note type by redownloading it from AnkiWeb
 - [x] I've tried to disable add-ons to see if there are any interactions present
 - [x] My issue disappears when I hold shift while starting Anki.
 - [ ] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?
2.1.57 windows

#### Error message (if any)

Anki client: Anki windows 2.1.57
Debug information
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.57 (6b7d372c) Python 3.9.15 Qt 6.4.2 PyQt 6.4.0
Platform: Windows-10-10.0.22621
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-01-30 21:47:32

Caught exception:
Traceback (most recent call last):
File "aqt.webview", line 43, in cmd
File "aqt.webview", line 150, in _onCmd
File "aqt.webview", line 614, in onBridgeCmd
File "aqt.hooks", line 5002, in call
File "C:\Users\Oracle\AppData\Roaming\Anki2\addons21\272311064\src\webview_init.py", line 90, in add_occlusion_messages
on_cloze(editor)
File "C:\Users\Oracle\AppData\Roaming\Anki2\addons21\272311064\src\editor_init.py", line 182, in on_cloze
return _old(editor)
NameError: name '_old' is not defined

**Comment by AnKingMed** [comment]
It looks like this is an error in the Closet add-on. Can you report it on that Github?
