### ISSUE TITLE
IO one by one not working in one profile

### ISSUE THREAD

**Issue by AnKingMed** [AnKing-Memberships/AnKing-Note-Types#116]
I have a weird conundrum. 

The IO-one by one note type on this collection doesn't work (the boxes don't show)
The IO-one by one (AnkiHub/ankingmed) note type works fine

As far as I can tell, the templates and styling are all the same. I've reset them multiple times with the note types add-on.

@RisingOrange can you look into this if you get 2 seconds?  I exported the entire collection and the closet css and js files (since I didn't export the media)

[example collection.zip](https://github.com/AnKing-Memberships/AnKing-Note-Types/files/10799609/example.collection.zip)

**Comment by RisingOrange** [comment]
@AnKingMed At first I imported the collection in a fresh Anki profile and couldn't reproduce the problem. 

Then I experimented a bit and noticed that the IO part doesn't work in some circumstances. 
(When there is a html comment at the end of the note type template (html comments look like this  ), but not at the top of the template. It is really weird and I don't understand why this happens.)

I made a change to the note type and created a new release for the AnKing note types add-on. Can you try resetting the note type with the new release of the add-on and see if it works for you then?

**Comment by AnKingMed** [comment]
That seems to have fixed the issue! Thanks for figuring that out. Do you think we should report it on the closet add-on or are we good for now?
