### ISSUE TITLE
Option to show card ease in the back of the card

### ISSUE THREAD

**Issue by BEST8OY** [AnKing-Memberships/AnKing-Note-Types#118]
#### Which Note Type (and version) is this about?
All of them

#### Checklist
 - [x] I've verified that I use the latest version of the note type by redownloading it from AnkiWeb
 - [x] I've checked if anyone else suggested this feature before by looking through the issue reports.

#### What Anki version are you using?
2.1.60
#### What Operating system are you using? (i.e. MacOS, Windows, Linux)
Windows 11

#### Problem case

*Is your feature request related to a problem?
Well it has many benefits
When reviewing a card if we see its Ease after answering it correctly we can decide

1-If the ease is really low we can use Easy button to increase the Ease instead of Good button which preserves the low ease.
It's beneficial to bring back Cards in ease hell to ease heaven!😅

2-if a card is too easy and we hit easy couple of time and the card has an ease like 300 we can decide from that point on stop hitting Easy and go with Good button for that specific card and not raising its ease too much

#### Solution

*Concisely describe the solution you would like*
An option to show ease percent in back of the card

**Comment by AnKingMed** [comment]
This addon does that https://ankiweb.net/shared/info/744725736
