### ISSUE TITLE
Option to show card info in the back of the cards

### ISSUE THREAD

**Issue by BEST8OY** [AnKing-Memberships/AnKing-Note-Types#119]
This addon does that https://ankiweb.net/shared/info/744725736

_Originally posted by @AnKingMed in https://github.com/AnKing-Memberships/AnKing-Note-Types/issues/118#issuecomment-1464979353_
            
Yes, but unfortunately it does not work on mobile as it's mentioned in the addon page.

And I mostly do my review with my phone on Ankiweb which is not possible to have addon on it.

Is it a limitation of Anki that this info cannot be implanted in card template?

**Comment by AnKingMed** [comment]
Yeah it's an Anki limitation. There's no way for the note type to pull that type of information (otherwise I would have done it already :)
