### ISSUE TITLE
Amboss and UWorld field

### ISSUE THREAD

**Issue by sugarycat** [AnKing-Memberships/AnKing-Note-Types#120]
#### Which Note Type (and version) is this about?

AnKingOverhaul--Release_1.1

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x ] I've verified that I use the latest version of the note type by redownloading it from AnkiWeb
 - [x ] I've checked if anyone else asked this question before by looking through the issue reports.
 - [ x] I've read through the README documents on this github and/or watched the tutorial video on the note types

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
⁨2.1.60 (76d88073)⁩
Python 3.9.15 Qt 6.4.2 PyQt 6.4.0
```

#### Your question

Hello,

Is there a particular reason why there is no field dedicated for Amboss and UWorld?
If possible, may I suggest that these fields be added to the AnKingOverhaul note type?

Thank you!

**Comment by AnKingMed** [comment]
That's what the missed questions field is for. Uworld and AMBOSS haven't given permissions to us to include their content for everyone so it didn't make sense to include a field for either of them
