### ISSUE TITLE
Max Image Height/Width Percent not working

### ISSUE THREAD

**Issue by marinalevo** [AnKing-Memberships/AnKing-Note-Types#124]
Since getting image support in AnkiHub, the new images are really large (won't fit without having to scroll) in size. When manipulating the Max Image Height in the most up-to-date add-on, nothing happens to images. Tried to make sure I hit "save" in the window, restarted anki, all of that with no avail.

I know I can manually change the height in edit but was hoping for a more broad solution. Thank you!!

**Comment by AnKingMed** [comment]
We're aware they're super big and we're going to try and minimize each of them. I'm not sure why the addon isn't working for this.. have you tried messing with the image width? Set it to 30% or 200px or something like that

**Comment by marinalevo** [comment]
Yes I tried that as well, it's weird, it changes the OME button/image when I change it but it doesn't fix the Extra field images!

**Comment by AnKingMed** [comment]
I figured out whats going on. If you search "width" in the styling you can manually find it. I'll have to push a change to the note type so that you can change it with the addon
