### ISSUE TITLE
Customize Auto open/field order based on tag

### ISSUE THREAD

**Issue by shmuelsash** [AnKing-Memberships/AnKing-Note-Types#125]
#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [X] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [X] I've checked if anyone else suggested this feature before by looking through the issue reports.

#### Problem case

I use Pixorize for some topics and Sketchy for others, however bec I use both I have both fields set to auto open which means I need to scroll past the images I don't need to find the one I learned the material with

#### Solution

Add the ability to have different field orders and/or different field auto open options based on a tag

#### More information

This will be especially useful when both sketchy fields have the new and old images, a user will be able choose which field they'd like  to see based on which video they learned the material from

**Comment by AnKingMed** [comment]
@abdnh do you know if this type of functionality is even possible? Can the JavaScript on the note read the tags?

**Comment by abdnh** [comment]
The tags can be read by including `{{Tags}}` in the template.
https://docs.ankiweb.net/templates/fields.html#special-fields

**Comment by abdnh** [comment]
Looks similar to #90
Should the tags be customizable? If so, we need to add new options to the notetypes add-on.

**Comment by AnKingMed** [comment]
Looks like you're right, it is similar to #90 

I think it should be tag `autoopen::Fieldname` or something like that, but not customizable behind the field name
