### ISSUE TITLE
One by one cloze hider can not be change

### ISSUE THREAD

**Issue by eva30u** [AnKing-Memberships/AnKing-Note-Types#129]
#### Which Note Type (and version) is this about? 
Anki 2.1

#### Problem description
When i try to change my cloze hider with and emoji or just dots and i save it sometimes it works but when you check again it didnt save anything and its in blank, and sometimes its sends and error when i save it.

*Please describe the issue concisely in here. In case of an error: Walk us through the steps you took to get there. What happened? What did you expect to happen?*

I check my anking overhaul or general
I change my cloze hider with a ? or ... or ❓
When i save it, it "work"
i check my questions with this type of card and there was no symbol or answer, even tho its written
I check again my overhaul and the cloze hider its in blank
I change it again
I saved it and when i did, it send and error

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x ] I've restarted Anki to see if it helps
 - [ ] I've verified that I use the latest version of the note type by redownloading it from AnkiWeb
 - [ x] I've tried to disable add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [ x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?
⁨2.1.61
*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.##
```
#### What Operating system are you using? (i.e. MacOS, Windows, Linux)
MacOS

*Please include OS version as well if possible*
Ventura 13.3

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```
#### Error message (if any)
```

**Comment by AnKingMed** [comment]
I'm not able to replicate this. You're talking about here?  Can you walk me through what you're doing and provide screenshots?
![image](https://user-images.githubusercontent.com/57678116/233806200-f525994f-77de-46fd-830c-4dc7c57c458a.png)

**Comment by eva30u** [comment]
Well i f up i check it again and now it didnt send error or anything, im sorryyy

**Comment by AnKingMed** [comment]
No worries:)
