### ISSUE TITLE
one by one next close reveal bug

### ISSUE THREAD

**Issue by bginsy** [AnKing-Memberships/AnKing-Note-Types#132]
#### Which Note Type (and version) is this about?
AnkingOverhaul

#### Problem description

shortcut to reveal/toggle one by one clozes are not working for all my cards. The only thing i can think of is that ive had two anking notetype updates back to back recently and now they just dont work.

*Please describe the issue concisely in here. In case of an error: Walk us through the steps you took to get there. What happened? What did you expect to happen?*

when i click N or , i expect it to toggle the one by one clozes but nothing happens.

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x ] I've restarted Anki to see if it helps
 - [ ] I've verified that I use the latest version of the note type by redownloading it from AnkiWeb
 - [x ] I've tried to disable add-ons to see if there are any interactions present
 - [x ] My issue disappears when I hold shift while starting Anki.
 - [x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.54
```
#### What Operating system are you using? (i.e. MacOS, Windows, Linux)

*Please include OS version as well if possible*
windows 10

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```

```

**Comment by bginsy** [comment]
Yes, ive been studying for my finals for today and tomorrow so ive been using anki constantly. 

Just attempted that and no difference. It looks to be like a majority of my cards using one-by-one don't work and there are a small amount that do work. I checked the note type and they are all the same too. 

They only work if i click "Reveal next" with my mouse. i tried to use a controller and it doesnt recognize the command/input either. but all other shortcuts work "e" will allow me to edit, etc. so its only the one-by-one shortcuts that arent registering. i tried changing the shortcut too and no difference.

**Comment by bginsy** [comment]
just found an error code trying on my ipad.

PS4 controller on ipad (current iOS)
left shoulder = action 1 = toggle all clozes
right shoulder = action 2 = reveal next cloze

im assuming shortcuts are problematic for me on all devices because this error so no controller or keyboard will work with one by one.

![anki error](https://user-images.githubusercontent.com/131873100/234636558-281192de-dac6-4275-8add-a500a56d3ce9.png)

**Comment by AnKingMed** [comment]
So it doesn't work on desktop and the user actions don't work on mobile? 

I'm not at home, but I just connected a keyboard to my iPad and the key `n` worked for me

**Comment by bginsy** [comment]
Just tried a keyboard on my ipad and the n didnt work still

**Comment by bginsy** [comment]
i made a card and it worked on the new profile.
for reference. those are my addons that i use normally on my profile.

![newuser](https://user-images.githubusercontent.com/131873100/234646110-5da251e2-d3a0-443a-a579-e7470048f8ad.png)
![image](https://user-images.githubusercontent.com/131873100/234646115-652ef54e-5475-4608-a33e-ecc74dbf0792.png)

**Comment by AnKingMed** [comment]
Next step is not holding shift when starting. Does it work with addons installed?

If so, try resetting the note type on your main profile

**Comment by AnKingMed** [comment]
Try copying the front, back and styling into your note styling. Maybe manually resetting will work?

https://github.com/AnKing-Memberships/AnKing-Note-Types/tree/master/Note%20Types/AnKingOverhaul

**Comment by bginsy** [comment]
Nope, didn't fix it either. i tried removing the contanki thinking it was that addon that was bugging it but didnt fix it either.

**Comment by AnKingMed** [comment]
Can you export one note that's not working and upload here?  You'll need to zip it

**Comment by bginsy** [comment]
[Selected Notes.zip](https://github.com/AnKing-Memberships/AnKing-Note-Types/files/11337700/Selected.Notes.zip)

**Comment by bginsy** [comment]
should be a card for arterial occlusion with 5 one by one clozes with anking note type

**Comment by AnKingMed** [comment]
I was able to reproduce this by importing into another profile. Then if I used the add-on to reset note types or import a new note type, none of them worked. I have no idea what's going on here

@abdnh can you look into this? I wonder if it's similar to https://github.com/AnKing-Memberships/AnKing-Note-Types/issues/116 except I made sure that the front/back templates and styling were identical to what they are in my personal profile and it wouldn't work. I'm not sure what's going on here

**Comment by AnKingMed** [comment]
Looks like importing into another profile doesn't work either. `n`, `'`, `,` don't work. `h` is working. 

I test all of this without add-ons

**Comment by AnKingMed** [comment]
@abdnh I figured it out. If the note **doesn't** have a tag, then the shortcuts don't work.
