### ISSUE TITLE
Text to speech note customizations

### ISSUE THREAD

**Issue by aubreyhong** [AnKing-Memberships/AnKing-Note-Types#140]
Hi, I would appreciate if the other fields on the anking cards can have a shortcut to make them text to speech. Currently I'm copying and pasting this everytime the note types get updated. 
{{tts en_US voices=Apple_Samantha,Microsoft_Zira speed=1.6:Extra}}
{{tts en_US voices=Apple_Samantha,Microsoft_Zira speed=1.6:Lecture Notes}}
{{tts en_US voices=Apple_Samantha,Microsoft_Zira speed=1.6:Sketchy}}
{{tts en_US voices=Apple_Samantha,Microsoft_Zira speed=1.6:First Aid}}
{{tts en_US voices=Apple_Samantha,Microsoft_Zira speed=1.6:Boards and Beyond}}
{{tts en_US voices=Apple_Samantha,Microsoft_Zira speed=1.6:Pathoma}}
{{tts en_US voices=Apple_Samantha,Microsoft_Zira speed=1.6:Missed Questions}}
Thanks

**Comment by AnKingMed** [comment]
This is a feature built into Anki so I don't think we can add extra shortcuts for this unfortunately
