### ISSUE TITLE
Auto-reveal hints based on tag

### ISSUE THREAD

**Issue by akavi1** [AnKing-Memberships/AnKing-Note-Types#90]
Anking Overhaul

There are options in the notetypes addon to auto reveal hints but this applies to all cards. It would be better if you could auto reveal the hint if the card had a particular tag. Sometimes I want the sketchy field to be shown by default, sometimes I want pixorize depending on which video I watched. This feature would allow you to specify which fields are shown on a per note basis.

Example: If the note has the AnKing_Reveal::Sketchy tag, then the Sketchy field will auto-reveal. If it has the AnKing_Reveal::Pixorize tag, then the Pixorize field will auto reveal. If it has AnKing_Reveal::Pixorize and AnKing_Reveal::First_Aid, then both the Pixorize and First Aid fields will reveal.

**Comment by Quaidge** [comment]
I have a solution which seems functional, though it has little testing. I wrote this assuming the fix from #101 is implemented.

First an object similar to ButtonAutoReveal (examples of usage included for Sketchy and Pathoma fields) is created to pair arrays of strings with their corresponding field:

```diff
<script>
// ##############  HINT REVEAL SHORTCUTS  ##############
// All shortcuts will also open with "H" if using the Hint Hotkeys add-on 
var ButtonShortcuts = { ... }
var ToggleAllButtonsShortcut = "'"
var ToggleNextButtonShortcut = "H";
// ##############  SHOW HINTS AUTOMATICALLY  ##############
var ButtonAutoReveal = { ... }

+var autoRevealTags = {
+    "Lecture Notes" : [],
+    "Missed Questions" : [],
+    "Pathoma" : ["#Pathoma"],
+    "Boards and Beyond" : [],
+    "First Aid" : [],
+    "Sketchy" : ["#SketchyMicro", "#SketchyPharm"],
+    "Sketchy 2": [],
+    "Sketchy Extra": [],
+    "Picmonic": [],
+    "Pixorize" : [],
+    "Physeo" : [],
+    "Bootcamp" : [],
+    "Additional Resources" : [],
+}

var ScrollToButton = true;

// ##############  TAG SHORTCUT  ##############
var toggleTagsShortcut = "Shift+C";
```
These objects may benefit from being combined as they serve a highly similar function.

Next, a couple new functions:

```js
<script>
  (function() {
    const revealHint = function(field) {
      const container = document.querySelector(`[data-name="${field}"]`)
      toggleHintBtn(container.id, noScrolling=true)

      // allows already existing method for revealing/hiding fields to take control,
      // assuming the fix from #101 is implemented
      ButtonAutoReveal[field] = true

      // hide revealed fields if this is a one by one card
      if (tagContainer.innerHTML.indexOf("^One_by_one") != -1) {
        const link = container.getElementsByTagName("a")[0]
        const button = container.getElementsByTagName("button")[0]
        const hint = container.getElementsByTagName("div")[0]
        button.classList.remove("expanded-button")
        hint.style.display = "none"
        link.style.display = ""
      }
    }

    // toggle specific fields according to specified tags
    for (const [field, tags] of Object.entries(autoRevealTags)) {
      // prevent conflicts with ButtonAutoReveal, otherwise function just closes auto-revealed fields
      if (ButtonAutoReveal[field] == true) continue

      // reveal field if specified tag is present in tagContainer
      for (const tag of tags) {
        if (tagContainer.innerHTML.indexOf(tag) != -1) {
          revealHint(field)
          break
        }
      }
    }
  })()
</script>
```

Issues I can currently think of:
- Adding tag-specific functionality limits the current implementation of ButtonAutoReveal to only fields which an individual would want to ALWAYS have revealed. This is why I suggest that combining these objects may be beneficial.
- As far as I can tell, this solution does not work on the current mobile beta (v20091.5). Not really sure why or know how to debug.
- My code might just be complete garbage. Let me know if it is, I really enjoy it as a hobby/distraction.
